# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy dependency definitions
COPY package.json package-lock.json* yarn.lock* ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the application
COPY . .

# Build TypeScript sources
RUN npx tsc

EXPOSE 8080

CMD ["node", "dist/index.js"]
